<?php

declare(strict_types=1);

/*
 * TestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestAPILib\Tests\Controllers;

use TestAPILib\Controllers\APIController;
use TestAPILib\Exceptions;

class APIControllerTest extends BaseTestController
{
    /**
     * @var APIController APIController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getAPIController();
    }

    public function testGetusers()
    {
        // Parameters for the API call
        $search = null;
        $limit = null;

        // Perform API call
        $result = null;
        try {
            $result = self::$controller->getusers($search, $limit);
        } catch (Exceptions\ApiException $e) {
        }

        $headers = [];
        $headers['Content-Type'] = ['application/json', true];

        // Assert result with expected response
        $this->newTestCase($result)->expectStatus(200)->allowExtraHeaders()->expectHeaders($headers)->assert();
    }
}
