<?php

declare(strict_types=1);

/*
 * TestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestAPILib\Tests;

use Core\Types\CallbackCatcher;
use TestAPILib\TestAPIClient;
use TestAPILib\TestAPIClientBuilder;

class ClientFactory
{
    public static function create(CallbackCatcher $httpCallback): TestAPIClient
    {
        $clientBuilder = TestAPIClientBuilder::init();
        $clientBuilder = self::addConfigurationFromEnvironment($clientBuilder);
        $clientBuilder = self::addTestConfiguration($clientBuilder);
        return $clientBuilder->httpCallback($httpCallback)->build();
    }

    public static function addTestConfiguration(TestAPIClientBuilder $builder): TestAPIClientBuilder
    {
        return $builder;
    }

    public static function addConfigurationFromEnvironment(TestAPIClientBuilder $builder): TestAPIClientBuilder
    {
        $timeout = getenv('TEST_API_LIB_TIMEOUT');
        $numberOfRetries = getenv('TEST_API_LIB_NUMBER_OF_RETRIES');
        $maximumRetryWaitTime = getenv('TEST_API_LIB_MAXIMUM_RETRY_WAIT_TIME');
        $environment = getenv('TEST_API_LIB_ENVIRONMENT');
        $defaultHost = getenv('TEST_API_LIB_DEFAULT_HOST');

        if (!empty($timeout) && \is_numeric($timeout)) {
            $builder->timeout(intval($timeout));
        }

        if (!empty($numberOfRetries) && \is_numeric($numberOfRetries)) {
            $builder->numberOfRetries(intval($numberOfRetries));
        }

        if (!empty($maximumRetryWaitTime) && \is_numeric($maximumRetryWaitTime)) {
            $builder->maximumRetryWaitTime(intval($maximumRetryWaitTime));
        }

        if (!empty($environment)) {
            $builder->environment($environment);
        }

        if (!empty($defaultHost)) {
            $builder->defaultHost($defaultHost);
        }

        return $builder;
    }
}
