<?php

declare(strict_types=1);

/*
 * TestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use TestAPILib\Models\UsersResponse;

/**
 * Builder for model UsersResponse
 *
 * @see UsersResponse
 */
class UsersResponseBuilder
{
    /**
     * @var UsersResponse
     */
    private $instance;

    private function __construct(UsersResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Users Response Builder object.
     */
    public static function init(): self
    {
        return new self(new UsersResponse());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new Users Response object.
     */
    public function build(): UsersResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
