<?php

declare(strict_types=1);

/*
 * TestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use TestAPILib\Models\UsersRequest;

/**
 * Builder for model UsersRequest
 *
 * @see UsersRequest
 */
class UsersRequestBuilder
{
    /**
     * @var UsersRequest
     */
    private $instance;

    private function __construct(UsersRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Users Request Builder object.
     *
     * @param int $age
     * @param \DateTime $signupDate
     */
    public static function init(int $age, \DateTime $signupDate): self
    {
        return new self(new UsersRequest($age, $signupDate));
    }

    /**
     * Sets username field.
     *
     * @param string|null $value
     */
    public function username(?string $value): self
    {
        $this->instance->setUsername($value);
        return $this;
    }

    /**
     * Sets is Active field.
     *
     * @param bool|null $value
     */
    public function isActive(?bool $value): self
    {
        $this->instance->setIsActive($value);
        return $this;
    }

    /**
     * Sets rating field.
     *
     * @param float|null $value
     */
    public function rating(?float $value): self
    {
        $this->instance->setRating($value);
        return $this;
    }

    /**
     * Initializes a new Users Request object.
     */
    public function build(): UsersRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
