<?php

declare(strict_types=1);

/*
 * TestAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TestAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use TestAPILib\Models\UsersResponse1;

/**
 * Builder for model UsersResponse1
 *
 * @see UsersResponse1
 */
class UsersResponse1Builder
{
    /**
     * @var UsersResponse1
     */
    private $instance;

    private function __construct(UsersResponse1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Users Response 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new UsersResponse1());
    }

    /**
     * Sets id field.
     *
     * @param int|null $value
     */
    public function id(?int $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Users Response 1 object.
     */
    public function build(): UsersResponse1
    {
        return CoreHelper::clone($this->instance);
    }
}
